automation:
  - id: "pid_values_update"
    alias: "pid_values_update"
    triggers: []
    conditions: []
    actions:
      - action: smart_thermostat.set_pid_gain
        data:
          kp: 16
          ki: 0.01
          kd: 4
        target:
          entity_id: climate.sercan_thermostat

      - action: smart_thermostat.set_pid_gain
        data:
          kp: 90
          ki: 0.08
          kd: 80
        target:
          entity_id: climate.misafir_thermostat

      - action: smart_thermostat.set_pid_gain
        data:
          kp: 30
          ki: 0.06
          kd: 80
        target:
          entity_id: climate.bebek_thermostat

      - action: smart_thermostat.set_pid_gain
        data:
          kp: 40
          ki: 0.02
          kd: 60
        target:
          entity_id: climate.melike_thermostat

      - action: smart_thermostat.set_pid_gain
        data:
          kp: 50
          ki: 0.02
          kd: 60
        target:
          entity_id: climate.banyo_thermostat

      - action: smart_thermostat.set_pid_gain
        data:
          kp: 40
          ki: 0.05
          kd: 60
        target:
          entity_id: climate.yatak_thermostat

      - action: smart_thermostat.set_pid_gain
        data:
          kp: 150
          ki: 0
          kd: 0
        target:
          entity_id: climate.salon_thermostat

    mode: single
